// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNl0BUcwEs673Go5WyU-ahimXtyAxxxLU',
    appId: '1:991735936662:web:44986023244eb478beb4b7',
    messagingSenderId: '991735936662',
    projectId: 'fluxdrop-1a9d7',
    authDomain: 'fluxdrop-1a9d7.firebaseapp.com',
    storageBucket: 'fluxdrop-1a9d7.firebasestorage.app',
    measurementId: 'G-TTFCQZPMQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVHNwS7JnFQQ1h0am_DGWG7GlIv27GvM',
    appId: '1:991735936662:android:69b34179a13e01b7beb4b7',
    messagingSenderId: '991735936662',
    projectId: 'fluxdrop-1a9d7',
    storageBucket: 'fluxdrop-1a9d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbP0bOvYIbkT3AAkb57jKutvV_Zc4ZHW8',
    appId: '1:991735936662:ios:62bf0f4cf05b2db0beb4b7',
    messagingSenderId: '991735936662',
    projectId: 'fluxdrop-1a9d7',
    storageBucket: 'fluxdrop-1a9d7.firebasestorage.app',
    iosBundleId: 'com.example.fluxdrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbP0bOvYIbkT3AAkb57jKutvV_Zc4ZHW8',
    appId: '1:991735936662:ios:62bf0f4cf05b2db0beb4b7',
    messagingSenderId: '991735936662',
    projectId: 'fluxdrop-1a9d7',
    storageBucket: 'fluxdrop-1a9d7.firebasestorage.app',
    iosBundleId: 'com.example.fluxdrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNl0BUcwEs673Go5WyU-ahimXtyAxxxLU',
    appId: '1:991735936662:web:4a3ac5e433350756beb4b7',
    messagingSenderId: '991735936662',
    projectId: 'fluxdrop-1a9d7',
    authDomain: 'fluxdrop-1a9d7.firebaseapp.com',
    storageBucket: 'fluxdrop-1a9d7.firebasestorage.app',
    measurementId: 'G-9K1VMNK366',
  );
}
